export { default as Lehrerverwaltung } from './admin/Lehrerverwaltung.vue'
export { default as Klassenverwaltung } from './admin/Klassenverwaltung.vue'
export { default as Planerkonto } from './admin/Planerkonto.vue'
export { default as Raumverwaltung } from './planer/Raumverwaltung.vue'
export { default as Stundendauer } from './planer/Stundendauer.vue'
export { default as Vertretungen } from './planer/Vertretungen.vue'